name: Update Macro Data Twice Daily

on:
  schedule:
    - cron: '0 0 * * *'     # 00:00 UTC
    - cron: '12 12 * * *'   # 12:12 UTC
  workflow_dispatch:        # Bisa dijalankan manual

jobs:
  run-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests supabase

      - name: Run macro data updater
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TRADINGECONOMICS_KEY: ${{ secrets.TRADINGECONOMICS_KEY }}
        run: python update_macro_data.py
